spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    password: letmein
    username: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true